Add three separate classes for person and update UI to display group
AY2324S2-CS2103T-F12-4/tp pull request #29
Opened 2024-03-22 14:23 UTC by dhlee03

Add three separate classes: Participant, Sponsor, Staff
Add factory method for Person
Add Group class
Update UI to display group.

2024-03-22 14:39 UTC, bachletuankhai requested changes
LSP is violated in `Participant::isSamePerson` and `Staff::isSamePerson`. They should not be more restrictive than `Person::isSamePerson`

2024-03-22 14:39 UTC, bachletuankhai commented on src/main/java/seedu/address/model/person/Staff.java
> +        return super.isSamePerson(otherPerson) && isSameGroup;
LSP violated here.

2024-03-22 14:58 UTC, dhlee03 commented
Most of implementations related to Group class are not currently done in this stage. Only getter and setter exist inside. It will be tested after some of its function is implemented.

2024-03-23 09:27 UTC, bachletuankhai approved these changes
LGTM

2024-03-23 09:27 UTC, bachletuankhai commented on src/test/java/seedu/address/model/person/GroupTest.java
> +    public void equals() {
`equals` does not cover all cases in `Group::equals`

2024-03-23 09:28 UTC, bachletuankhai commented on src/test/java/seedu/address/model/person/GroupTest.java
> +    public void equals() {
Just to point out what could be improved, the overall coverage and important test cases are good enough.

2024-03-23 09:28 UTC, merged